name: Docker Image CI

on:
  push:
    branches: [ main ]
  

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write # 🟢 อนุญาตให้หุ่นยนต์เขียนทับ Image เดิม (Push ขึ้น GHCR ได้)
      contents: read
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry (ghcr.io)
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }} # 🟢 ดึงชื่อผู้ใช้ GitHub มาใช้อัตโนมัติ
          password: ${{ secrets.GITHUB_TOKEN }} # 🟢 ใช้ Token พิเศษของ GitHub อัตโนมัติ

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          # 🟢 ใช้ github.repository_owner เพื่อให้โค้ดปรับตามชื่อ GitHub ของผู้เรียนอัตโนมัติ
          tags: ghcr.io/ncotista/auto-web:latest
